// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace blazor_orderbook_simulation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("filled")
                        .HasColumnType("TEXT");

                    b.Property<int>("order_side")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("remaining")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("order_id");

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("OrderType").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tradelog", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("execution_price")
                        .HasColumnType("TEXT");

                    b.Property<int>("maker_id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("taker_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("log_id");

                    b.HasIndex("maker_id");

                    b.HasIndex("taker_id");

                    b.ToTable("TradeLogs");
                });

            modelBuilder.Entity("LimitOrder", b =>
                {
                    b.HasBaseType("Order");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Limit");
                });

            modelBuilder.Entity("MarketOrder", b =>
                {
                    b.HasBaseType("Order");

                    b.HasDiscriminator().HasValue("Market");
                });

            modelBuilder.Entity("Tradelog", b =>
                {
                    b.HasOne("Order", "Maker")
                        .WithMany("MakerTrades")
                        .HasForeignKey("maker_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Order", "Taker")
                        .WithMany("TakerTrades")
                        .HasForeignKey("taker_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maker");

                    b.Navigation("Taker");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("MakerTrades");

                    b.Navigation("TakerTrades");
                });
#pragma warning restore 612, 618
        }
    }
}
